export const PROJECT_FORM = "PROJECT_FORM";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const FORM_VALIDATION = "FORM_VALIDATION";
export const ACTUAL_PROJECT = "ACTUAL_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const TASK_ERROR = "TASK_ERROR";
export const DELETE_TASK = "DELETE_TASK";
export const TASK_STATUS = "TASK_STATUS";
export const SELECTED_TASK = "SELECTED_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const CLEAR_SELECTED_TASK = "CLEAR_SELECTED_TASK";
